### ISSUE TITLE
Fix dependencies in Windows.

### ISSUE THREAD

**Issue by saurabhshri** [saurabhshri/CCAligner#10]
For grammar and language models generation, CCAligner has some dependencies. Current implementation requires user to have them installed and the code calls them using system calls and then process it's output. It currently works only on Linux/Unix.

Both the dependencies can be compiled on Windows (List: https://github.com/saurabhshri/CCAligner#installing-dependencies). Relevant file : (https://github.com/saurabhshri/CCAligner/blob/master/src/lib_ccaligner/grammar_tools.cpp).

Add support for these dependencies in Windows.

**Comment by harrynull** [comment]
Fixed in #21 
I think it can be closed now.

**Comment by saurabhshri** [comment]
@harrynull Yep, thanks! From next time you may close issues directly from your PR by including any of the keywords mentioned here : https://help.github.com/articles/closing-issues-using-keywords/ . ;)
