### ISSUE TITLE
CCAligner crashes while recognizing and aligning 

### ISSUE THREAD

**Issue by HemangRajvanshy** [saurabhshri/CCAligner#37]
Following commit https://github.com/saurabhshri/CCAligner/commit/96ce9a76870834c72d77eeea859ca5b960b697a4

CCAligner crashes after initializing the pocketsphinx decoder. Note that the program runs successfully on previous commits with same input files and parameters.  
OS: Windows 7
Parameters: default (-wav file -srt file)
The program also runs with transcription turned on. 

![capture](https://user-images.githubusercontent.com/9369400/33537055-7b61abbc-d8df-11e7-9700-a80760208e25.JPG)

![capture](https://user-images.githubusercontent.com/9369400/33537063-a2a68bca-d8df-11e7-9831-cc9acbc82fcc.JPG)

**Comment by Rakete1111** [comment]
Do this bug also appear on master from your part?

**Comment by HemangRajvanshy** [comment]
Yes, the bug is on every commit following the mentioned commit.

**Comment by saurabhshri** [comment]
@HemangRajvanshy Could you please try the latest master? If the issue still persists, feel free to re-open the issue.

**Comment by HemangRajvanshy** [comment]
Fixed!
