### ISSUE TITLE
Reverse-Inception?

### ISSUE THREAD

**Issue by The-Bart-The** [saurabhshri/CCAligner#73]
Not a bug, but an enhancement / feature request.

How about going one layer shallower and support converting transcripts (txt) to subtitles (srt) (example: [https://www.grc.com/sn/sn-676.txt](https://www.grc.com/sn/sn-676.txt) for the audio from https://www.youtube.com/watch?v=stUjByfyLfk )?  This would remove the biggest burden (synchronization) from subtitling.  It looks like you already did the heavy lifting.

Just a thought; thanks for your time.

**Comment by saurabhshri** [comment]
@The-Bart-The Since, the output can be obtained in both XML and JSON format, it's only the matter of parsing through those and create subtitles. Sounds like a fun side project. 🙂 Feel free to send a pull request. I will also create a GCI task with this issue.

**Comment by saurabhshri** [comment]
Closing, since it can be handled externally. Feel free to re-open in case you think this needs to be a part of CCAligner. We can think more about it. 

Thanks!
