### ISSUE TITLE
Failed to create recognizer

### ISSUE THREAD

**Issue by T1duS** [saurabhshri/CCAligner#75]
So, I have been trying to install ccaligner since a few days, getting different errors mostly related to dependencies. I even tried installing it in a factory new ubuntu 18.04 lts. I am getting this error.
Screen shot --
![screenshot from 2018-10-02 19-22-37](https://user-images.githubusercontent.com/42933260/46353043-db27e480-c678-11e8-9376-cfac4f68b231.png)

**Comment by saurabhshri** [comment]
Could you please post the content of the log files which were created too?

[On the sidenote : we can do much better with the error messages]

**Comment by T1duS** [comment]
https://pastebin.com/cBERN3C5

**Comment by saurabhshri** [comment]
@T1duS The one mentioned in the 'logpath' in terminal output. :)

**Comment by saurabhshri** [comment]
From your logs 

> ERROR: "dict.c", line 275: Failed to open dictionary file 'tempFiles/dict/complete.dict' for reading: No such file or directory

CCAligner doesn't find dictionary to work with. Also, from logs I can see that it did not even attempt to create any grammar files.

> 10-02 19:19:15][Verbose] grammarType         : 9
 
tells me that you're using `--generate-grammar no`.

If you do not want to generate grammar files, you need to have them already and then pass to CCAligner using parameters mentioned under the heading **Grammar, Language Model related parameters** in the readme.

It's recommended to let it generate grammar files on its own unless you have them prepared already.

Moreover regarding dependencies, I see that some dependencies have made breaking changes. I'd recommend to install all the dependencies from the mirror mentioned in the readme until the changes are reflected here (or maybe send a PR with the changes 😉)

Feel free to re-open this issue, if it doesn't solve your problem , or open another one if you encounter something else! 😄

**Comment by T1duS** [comment]
I have tried to run it without --generate-grammar, it's still giving the same error

**Comment by T1duS** [comment]
Oh, my bad, I tested without --generate-grammar no in my previous system, not in this one. Its working fine now thanks :D

**Comment by saurabhshri** [comment]
@T1duS Great! 🎉  Also, if you found out any missing information, feel free to send update that by sending a PR! 🙂

**Comment by T1duS** [comment]
Missing information?

**Comment by joseamair** [comment]
i'm having the same issue. 
Im using the following command:
`./ccaligner -wav ../test/data/goforward.wav -srt ../test/data/goforward.srt --generate-grammar no`
With the provided test file of the repository. 

The g2g setup.py test ran with success. 
I cant get it work.

**Comment by joseamair** [comment]
https://pastebin.com/Nbtyp6TW
Here is my log.

**Comment by saurabhshri** [comment]
@joseamair Sorry for the super-late reply, if you're passing `--generate-grammar no`, then you need to pass all the grammar files manually. If you want CCAligner to generate them for you, skip `--generate-grammar` parameter.

Let me know if the docs help, and if not, how can I improve them.
