### ISSUE TITLE
Tested CCAligner

### ISSUE THREAD

**Issue by MakarovGCI2018** [saurabhshri/CCAligner#79]
I checked errors in CCAligner. First of all i checked if it processed right damaged files or files with wrong extension(not .wav files) and also files .wav but with wrong parameters(not those: 16 bit PCM mono sampled at 16KHz). 
Then i run right file but with wrong parameters, and process was aborted with error: InvalidParameters. After all i run CCAligner with correct options and got .srt file with subtitles inside.

1.Tried to open file that doesn't exist, and then to open file that exist but with wrong extension(Error was handled)+
![wrong_file](https://user-images.githubusercontent.com/44312997/47776654-946eee00-dcfb-11e8-82fc-95742dedc110.png)

2.Tried to process file without grammar installed on my computer(Error was handled)+
![right_wav_file](https://user-images.githubusercontent.com/44312997/47776656-946eee00-dcfb-11e8-971c-d8ec982a9be7.png)

3.Tried to process file without right options(not those: 16 bit PCM mono sampled at 16KHz). (Error was handle)+
![file_with_wrong_wav](https://user-images.githubusercontent.com/44312997/47776669-9e90ec80-dcfb-11e8-9848-4b0ab88898be.png)

4.Run CCAligner with wrong parameters(Error was handled)+
![wrong_parameters](https://user-images.githubusercontent.com/44312997/47776653-946eee00-dcfb-11e8-977d-8f91fcd1fce0.png)

5.Changed manually .wav file to damage it and processed using CCAligner. I opened file with text editor and added a few symbols that mustn't be there such as random letters and numbers. After that file became damaged(There are a few noises that you can hear by playing that file). Then I got an error "Core dumped" which wasn't handled(Error wasn't handled)-
![error](https://user-images.githubusercontent.com/44312997/47796897-ecbee380-dd2d-11e8-8a4d-78510c931416.png)

**Damaged file:
https://drive.google.com/open?id=1Xx8fm2louuJg_VNbW6l0Izbl5SgfgRLG

**Comment by MakarovGCI2018** [comment]
I close this issue, because it was fixed in current master by pr #81

**Comment by saurabhshri** [comment]
Thanks!
