### ISSUE TITLE
Segmentation fault (core dumped) stops the program immediately

### ISSUE THREAD

**Issue by darksipu** [saurabhshri/CCAligner#83]
Any ideas on this 'Segmentation fault (core dumped)' error? I'm running on Ubuntu 16.04 and made sure to resample the audio files.

Cheers
[
![screenshot 2018-11-20 at 17 17 38](https://user-images.githubusercontent.com/15602688/48790972-81db4980-ece8-11e8-8a07-f721cb9211fa.png)
](url)

**Comment by MakarovGCI2018** [comment]
@darksipu please provide us the sample so we will able to solve this problem

**Comment by saurabhshri** [comment]
@darksipu Thanks for the report, closing as sample is needed to test this and it's been inactive for some time. Feel free to re-open this once!
