### ISSUE TITLE
[Feature Request] Changing the way information is displayed

### ISSUE THREAD

**Issue by MakarovGCI2018** [saurabhshri/CCAligner#86]
Now we can see a lot of data printed to stdout in report. I mean not only [Info] and [Fatal] but also [Debug] and [Verbose].

![data_in_stdout](https://user-images.githubusercontent.com/44312997/50056941-87537480-016c-11e9-9fef-c3f4bf511496.png)
In my opinion there is too much data for user to read.So I suggest not to print [Debug] and [Verbose] in normal mode and add option like -debug(or something like that) to print this data.

**Comment by saurabhshri** [comment]
Do the parameters listed under `Display related parameters` at https://github.com/saurabhshri/CCAligner#usage-parameters not work?

**Comment by MakarovGCI2018** [comment]
A parameter -verbosity covers all those suggestions for improvement
